CREATE TABLE auth_requests(
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  nonce VARCHAR NOT NULL,
  consumed_at TIMESTAMP WITH TIME ZONE NULL
);
SELECT diesel_manage_updated_at('auth_requests');
